### ISSUE TITLE
[decyzja] kupno domeny .pl

### ISSUE THREAD

**Issue by piotrl** [Olcia90079/ProjektZespolowy#19]
Żeby projekt zyskał profesjonalnego wyglądu, możemy rozważyć domenę .pl

Projekt niekoniecznie musi być drogi, często pierwszy rok kosztuje około 10zł ;) np. tutaj https://www.ovhcloud.com/pl/domains/tld/pl/

<img width="788" alt="image" src="https://user-images.githubusercontent.com/290300/202034628-663f4fa4-bcc1-41ce-86d4-b8e8dc310d0e.png">

Nie trzeba przedłużać.

Alternatywą byłoby subdomena do zapytania z inf.ug.edu.pl

**Comment by AgnKam** [comment]
Po konsultacjach z Panią Hanną dowiedziałyśmy się, że będzie nam udostępniona maszyna wirtualna i aplikacja będzie działać w domenie UG.
