### ISSUE TITLE
Integracja aplikacji z QR

### ISSUE THREAD

**Issue by Olcia90079** [Olcia90079/ProjektZespolowy#34]
- jak otworzyć aparat?
- jak przekazać zdjęcie z telefonu do przeglądarki?
- stworzyć kody QR przypisane do tablic
- wydrukować kody QR
- implementacja w kodzie (strona + funkcjonalność skanowania kodów + mapowanie)
- eksperyment zawartości kodu QR jako 

1. tekst zawierający jedynie identyfikator tablicy
2. link bezpośredni do tablicy

**Comment by piotrl** [comment]
Można użyć: https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API

```
barcodeDetector
  .detect(imageEl)
  .then((barcodes) => {
    barcodes.forEach((barcode) => console.log(barcode.rawValue));
  })

```
